#ifndef BUTTON_CONFIG_H_
#define BUTTON_CONFIG_H_

#include "classic_controller.h"

#define CLASSIC_CONTROLLER_LEFT_AMIGA_MOUSE_BUTTON    CLASSIC_BTN_a
#define CLASSIC_CONTROLLER_MIDDLE_AMIGA_MOUSE_BUTTON  CLASSIC_BTN_x
#define CLASSIC_CONTROLLER_RIGHT_AMIGA_MOUSE_BUTTON   CLASSIC_BTN_b
#define CLASSIC_CONTROLLER_HALF_SPEED_BUTTON          CLASSIC_BTN_rZ
#define CLASSIC_CONTROLLER_QUATER_SPEED_BUTTON        CLASSIC_BTN_rT


#endif