#ifndef BUTTON_CONFIG_H_
#define BUTTON_CONFIG_H_

#include "classic_controller.h"

#define CLASSIC_CONTROLLER_LEFT_AMIGA_MOUSE_BUTTON    CLASSIC_BTN_a
#define CLASSIC_CONTROLLER_MIDDLE_AMIGA_MOUSE_BUTTON  CLASSIC_BTN_x
#define CLASSIC_CONTROLLER_RIGHT_AMIGA_MOUSE_BUTTON   CLASSIC_BTN_b
#define CLASSIC_CONTROLLER_HALF_SPEED_BUTTON          CLASSIC_BTN_rZ
#define CLASSIC_CONTROLLER_QUATER_SPEED_BUTTON        CLASSIC_BTN_rT

#define CLASSIC_CONTROLLER_JOYSTICK_ACTION_BUTTON_A   CLASSIC_BTN_x
#define CLASSIC_CONTROLLER_JOYSTICK_ACTION_BUTTON_B   CLASSIC_BTN_y
#define CLASSIC_CONTROLLER_JOYSTICK_JUMP_BUTTON_A     CLASSIC_BTN_a
#define CLASSIC_CONTROLLER_JOYSTICK_JUMP_BUTTON_B     CLASSIC_BTN_b
#define CLASSIC_CONTROLLER_JOYSTICK_UP                CLASSIC_BTN_up
#define CLASSIC_CONTROLLER_JOYSTICK_DOWN              CLASSIC_BTN_down
#define CLASSIC_CONTROLLER_JOYSTICK_LEFT              CLASSIC_BTN_left
#define CLASSIC_CONTROLLER_JOYSTICK_RIGHT             CLASSIC_BTN_right


#endif